spring.application.name=zootropolis

# Credenziali e stringa di connessione a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/zootropolis?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.zootropolis=DEBUG
logging.file.name=logs/zootropolis.log

# Configurazione Mock GPS per UC-03
# Imposta a 'true' se vuoi che il GPS rilevi la posizione in automatico
# Imposta a 'false' se vuoi testare l'eccezione (EccezionePosizioneMancante -> Flusso 2.a)
app.gps.mock.enabled=true
app.gps.mock.default-location=Via Roma 10, Zootropolis